### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by dkraczkowski** [bluenote10/yachalk#14]
Is this library still maintained? I see CI is failing for the past 6 months and none attempted to fix it.

**Comment by bluenote10** [comment]
> Is this library still maintained?

Yes, absolutely!

> I see CI is failing for the past 6 months and none attempted to fix it.

Oh, why did I not get notified? 😕 Will have a look soon.

In any case this must be something rather trivial (false negative failure), because the library is in active use and working just fine.

**Comment by bluenote10** [comment]
Okay, CI should be running again. The issue was merely that ubuntu:latest had dropped support for Python 3.6.

**Comment by dkraczkowski** [comment]
@bluenote10  Thanks a lot!
