### ISSUE TITLE
Unsolved mystery with .rgb and .hex

### ISSUE THREAD

**Issue by charliemb2** [bluenote10/yachalk#16]
Bluenote10,  Thanks for such an awesome implementation of Chalk.  I'm really enjoying using it.  It works great and very intuitively except for the following.

Under the same VSCode environment, executing python code within VSCode's integrated terminal (which I believe is a full blown Powershell), both `.rgb` and `.hex` fail to portray any color other than white on black (which are the default).  It works in one file and not in another.  __Yet, in both files, all property-decorated methods work,__ like .red, .cyan, .gray, .green, red_bright, etc.  In the failing file, of the four non-decorated methods, at least `.rgb` and `.hex` don't work (I've not tested `.bg_rgb` nor `.bg_hex`).

In the python file where it doesn't work, I can independently fire up a Powershell and manually run it and it still fails.  So it fails similarly outside of the VSCode environment.

chalk.get_color_mode() verifies that both python files are running in true color mode.

One difference is the variety of modules I import.  In the file that fails I'm importing as follows:
```
import pandas
import pandas_market_calendars as market_calendar
import pathlib
from datetime import datetime, date, timedelta

from yachalk import chalk
```
Above, the only non-prolific import is the `market_calendar` but since .get_color_mode() indicates true color I doubt that this import changes things relative to color.  All it does is keep a pandas database of the stock market calendars.

Might you have any idea how this could be happening?  

Thanks,

Charlie

P.S.  E.g., The following line of code succeeds in one python file and fails in the other: 
```
print(chalk.rgb(170, 120, 0)("This is a string without a newline and I want to know what happens after no newline."))
```

**Comment by bluenote10** [comment]
It is not so easy for me to help, because I cannot directly reproduce the problem, but here are a few things you can try.

Note that color support is in general a property of the terminal. At import time, `yachalk` determines the supported color mode by the terminal by this logic:

https://github.com/bluenote10/yachalk/blob/49d14ce2b63899e8464e1863570daee78180310a/yachalk/supports_color.py#L39-L140

In principle importing another third party package _could_ mess up the logic if they e.g. change the `TERM` environment variable or so (which they really should not do!). You can try if that's the case by running something like:

```py
from yachalk.supports_color import detect_color_support
print(detect_color_support()) # Should print: ColorMode.FullTrueColor

# import all other packages/modules here...

print(detect_color_support()) # Still ColorMode.FullTrueColor?
```

In the terminal/context where the output isn't colored, you could also try if the coloring works on the terminal side at all: If yachalk has detected TrueColor support the expression `chalk.rgb(170, 120, 0)("TEST STRING")` simply gets converted to a string with embedded color codes: `'\x1b[38;2;170;120;0mTEST STRING\x1b[39m'`. So just place the following print in you script to see if it would output something colorful in general.

```py
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
```

If it does, it would indicate that it is indeed an issue of the color detection. Note that you could also enforce the color mode e.g. via `chalk.enable_full_colors()`.

**Comment by charliemb2** [comment]
Thanks.  That was a great response and helped me get to where I am now.  

`print(detect_color_support())` reports ColorMode.FullTrueColor both before and after the offending import statement (tqdm below) alters program environment so that only basic decorated colors work.  The following code:
```
print(detect_color_support()) # Still ColorMode.FullTrueColor?
# >>>>> Import the culprit library here. <<<<<<

print(detect_color_support()) # Still ColorMode.FullTrueColor?
chalk.enable_full_colors()
print('\x1b[34mTEST STRING\x1b[39m')
print('\x1b[34mTEST STRING\x1b[0m')
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
print('\x1b[38;2;17;100;0mTEST STRING\x1b[39m')
```
results in,
![image](https://github.com/bluenote10/yachalk/assets/11827749/e79f312b-daef-437d-bdff-1af6fc0ecb73)

Note that `chalk.enable_full_colors()` didn't change the above behavior.

After a lot of recursive digging I found that the offending library comes from 
```from tqdm import tqdm```.  
tqdm is a package that displays any iterable as a progress bar.

The only mention of color on the PyPi page for tqdm is "colorama," in ["Windows: additionally may require the Python module colorama to ensure nested bars stay within their respective lines."](https://pypi.org/project/tqdm/)  This isn't a color issue and I don't know if colorama can solve my issue but I'd hate to have to import colorama when I want to work exclusively with yachalk.  (tqdm lists colorama as a dependency and `pip show colorama` confirms it's installation.)

As `chalk.enable_full_colors()` didn't restore color for chalk itself, might there be another command within yachalk that can restore 38;2 codes (as used by chalk.rgb()) within the environment of the running program?  I don't think it's the terminal because other programs work properly when run immediately after the failing program exits, all from VSCode.  

Thanks

**Comment by bluenote10** [comment]
If your print of `print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')` is not colored any more, than there is nothing yachalk can do. All it can do is output exactly these codes, which it does, and they are supposed to be colored. This would mean that `tqdm` fundamentally messes up the terminal capabilities. To verify, when you run the following snippet is the first print colored, and the second isn't?

```py
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
from tqdm import tqdm
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
```

If so, you should probably raise that as a minimal reproducing issue for tqdm to solve it there.

**Comment by charliemb2** [comment]
Agreed.  Thanks.  You're dead on.

For anyone who may experience a similar problem, check to see if any library imports colorama v. 4.5.  It can leave the environment in an erroneous state.  To wit, the following code:
```
import colorama
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
colorama.init()
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
colorama.deinit()
print('\x1b[38;2;170;120;0mTEST STRING\x1b[39m')
```
results in,
![image](https://github.com/bluenote10/yachalk/assets/11827749/fb4af1e5-be81-4407-b289-9199886091ae)

Upgrading colorama to at least  v. 4.6 solved the problem.

**Comment by bluenote10** [comment]
Very interesting, thanks for sharing this finding!
