### ISSUE TITLE
Inverse

### ISSUE THREAD

**Issue by charliemb2** [bluenote10/yachalk#17]
The documentation lists inverse as one of the modifiers.  When I tried it I received an `AttributeError: 'ChalkBuilder' object has no attribute 'inverse'`.  Sure enough, peeking into ChalkBuilder after turning off autosave I can confirm that there is in fact no definition for inverse.

I can see where `inverse` would be handy, and while it's not the end of the world if it isn't implemented, I'm compelled to ask.. what's the plan, to update the documentation, to eventually implement it?

Thanks.

**Comment by bluenote10** [comment]
Thanks to @Mani4D46 this has been added in #19 and released in version [`0.1.6`](https://pypi.org/project/yachalk/#history).
